import time
from selenium import webdriver
driver=webdriver.Chrome()
driver.get('https://www.instagram.com/')
time.sleep(3)
driver.maximize_window()
username=driver.find_element_by_name('username').send_keys('gourav_shimli')
password=driver.find_element_by_name('password').send_keys('jcnruad@2432')
loginButon=driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]/button/div').click()
# password.submit()
time.sleep(7)
driver.get('https://www.instagram.com/explore/tags/gymlife/')
time.sleep(5)
posts=driver.find_element_by_xpath('//*[@id="react-root"]/section/main/article/div[2]/div/div[1]/div[1]/a/div/div[2]').click()
time.sleep(5)
# driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
comment=driver.find_element_by_xpath('/html/body/div[5]/div[2]/div/article/div[3]/section[1]/span[1]/button/div/span/svg')
comment.click()
print("hii")

# comment.clear()
# comment.send_keys('Hey Nice babe')
# print("hiiiiii")
# comment.send_keys(Keys.RETURN)
# postButton=driver.find_element_by_xpath('/html/body/div[5]/div[2]/div/article/div[3]/section[3]/div/form/button[2]')
# postButton.click()
# likeButton=driver.find_elements_by_class_name('QBdPU')
# print(likeButton[1].text)
# for post in posts:
#     posts[post].click()
#     time.sleep(3)
# driver.close()